# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bergercookie's thoughtstream
email: nickkouk@gmail.com
author: Nikos Koukis


# TODO - Post link to md file that describes your open-source uploaded codes
# Post a link to your CV - Copy your CV here when and when that happens git
# commit again here.

description: > # this means to ignore newlines until "baseurl:"
    Code code, robots, code, robots, robots, code... you get the point.. :-)

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bergercookie12
github_username:  bergercookie
so_username: bergercookie
so_id: 2843583

linkedin_username: nikos-koukis
linkedin_id: a1564885

# Build settings
markdown: kramdown
theme: minima

gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
